#!/bin/sh
# A utility for changing security group of Cloud9 EC2 instance

sg=sg-054ec61b3dff74138
operation=$1
export AWS_DEFAULT_PROFILE=china

if [ -z "$operation" ]
then
    echo "Usage: $0 on/off"
    aws ec2 describe-security-groups --group-id $sg
    exit 1
elif [ $operation == "on" ]
then
    echo "Adding rules for security group ..."
    aws ec2 authorize-security-group-ingress --group-id $sg --protocol tcp --port 22 --cidr 0.0.0.0/0
    aws ec2 authorize-security-group-ingress --group-id $sg --protocol tcp --port 8181 --cidr 0.0.0.0/0
    echo "Link for Cloud9: http://52.82.99.59:8181"
    exit 0
elif [ $operation == "off" ]
then
    echo "Removing rules for security group..."
    aws ec2 revoke-security-group-ingress --group-id $sg --protocol tcp --port 22 --cidr 0.0.0.0/0
    aws ec2 revoke-security-group-ingress --group-id $sg --protocol tcp --port 8181 --cidr 0.0.0.0/0
    exit 0
else
    echo "Usage: $0 on/off"
    exit 1
fi